### ISSUE TITLE
[enhancement] Module: Advanced CI/CD

### ISSUE THREAD

**Issue by desteves** [pulumi/foundational-training#23]
We need an exercise for multiple stacks. (Two is sufficient: dev and prod.)

How should we preview? How should we update? What do we do if something goes wrong between the two? (Definitely want trunk-based if possible, not long-running branches, but see below.)

However we do it for Pulumi Cloud is what we should recommend here. (I think we have a manual release workload for the prod env, but not entirely sure.)

**Comment by jkodroff** [comment]
There is no advanced CI/CD - there's just 1 module on CI/CD.
